### ISSUE TITLE
Failing to install 019 on iOS 10.3.1 iPhone 6 Plus

### ISSUE THREAD

**Issue by arinc9** [julioverne/Ext3nder-Installer#3]
![img_0097](https://user-images.githubusercontent.com/29339981/42422192-7c02ec4c-82ea-11e8-858a-049da39391b0.PNG)

**Comment by Titanius** [comment]
Same Problem after Update Ext3nder Installer to 020. iPhone 7 10.1.1 Now i can´t install Ext3nder Installer and now do not have Ext3nder anymore. Same Problem as Screenshot.

**Comment by arinc9** [comment]
Fixed with 020a. Thanks.
