### ISSUE TITLE
Xcode 7.3 Error ?

### ISSUE THREAD

**Issue by KangHidro** [julioverne/Ext3nder-Installer#8]
Hi, can you tell me that why I got this issues:

> provision.cpp:81
> ios/listAllDevelopmentCerts=3018
> Please update to Xcode 7.3 or later to continue developing with your Apple ID.

Ext3nder version 22a
iOS: 10.3.1
Device: iPhone 6S Plus (iPhone8,2)
Platform: N66mAP
Jailbreak: DoubleH3lix

Thank you very much!

**Comment by 0n** [comment]
Seems like it should be fixed in 022b, can you try to update it ?

**Comment by KangHidro** [comment]
It worked! Love 3000 times <3
